language: php

addons:
    apt:
        packages:
        - apache2
        - postfix
        - libapache2-mod-fastcgi
        - libappindicator1
        - fonts-liberation

cache:
  directories:
    - $HOME/.composer/cache

sudo: required
dist: trusty

php:
    - "7.1"
    - "7.2"

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled
        - MODULE_DIR=/tmp/coinbase
        - MODULE_SCRIPTS_DIR=/tmp/coinbase/tools

    matrix:
        - PS_VERSION=develop
        - PS_VERSION=1.7.4.x
        - PS_VERSION=1.7.5.x
        
    allow_failures:
        - php: 7.2       

    fast_finish: true        
    
before_script:
    #   Move Module to Tmp Folder
    - bash tools/move_module.sh
    #   Get Prestashop
    - bash $MODULE_SCRIPTS_DIR/get_prestashop.sh
    #   Setup WebServer (Apache & PHP-Fpm)
    - bash $MODULE_SCRIPTS_DIR/install_webserver.sh
    #   Install Prestashop (Composer & More)
    - bash $MODULE_SCRIPTS_DIR/start_prestashop.sh
    #   Install Module
    - bash $MODULE_SCRIPTS_DIR/install_module.sh coinbase
    
script: 
    - cd $MODULE_DIR
    - cd $TRAVIS_BUILD_DIR/modules/coinbase
    - phpunit -c phpunit.xml
        
notifications:
  email:         
    on_success: never
    on_failure: always
